#!/bin/bash

# Создаем директорию .ssh, если она не существует
mkdir -p ~/.ssh

# Убедимся, что файл authorized_keys существует, и установим правильные разрешения
touch ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys

# Читаем стандартный ввод (в нашем случае, это будет публичный SSH-ключ) и добавляем его в authorized_keys
while IFS= read -r line; do
    echo "$line" >> ~/.ssh/authorized_keys
done

# Установим правильные разрешения на директорию .ssh
chmod 700 ~/.ssh

echo "SSH-ключ добавлен в authorized_keys."
